const allHumanitiesData = [
            // --- Grupo [1135] ---
            { id: 'EDU70I', name: 'EDUCAÇÃO ESPECIAL E PROCESSOS INCLUSIVOS', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 10, y: 5.0, type: 'humanities' },
            { id: 'EDU70K', name: 'TECNOLOGIAS DIGITAIS NA EDUCAÇÃO', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 30, y: 5.0, type: 'humanities' },
            { id: 'ELO91', name: 'ÉTICA, PROFISSÃO E CIDADANIA', dependencies: [], groupId: '[1135]', period: 4, chs: 2, cht: 30, x: 50, y: 5.0, type: 'humanities' },
            { id: 'FCH7FA', name: 'FILOSOFIA DA CIÊNCIA E DA TECNOLOGIA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 70, y: 5.0, type: 'humanities' },
            { id: 'FCH7FC', name: 'TEORIA DAS CIÊNCIAS HUMANAS', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 90, y: 5.0, type: 'humanities' },
            { id: 'FCH7GA', name: 'METROPOLIZAÇÃO CONTEMPORÂNEA: TECNOLOGIA E TERRITÓRIO', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 10, y: 15.0, type: 'humanities' },
            { id: 'FCH7HA', name: 'HISTÓRIA DA TÉCNICA E DA TECNOLOGIA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 30, y: 15.0, type: 'humanities' },
            { id: 'FCH7HB', name: 'HISTÓRIA GERAL DA ECONOMIA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 50, y: 15.0, type: 'humanities' },
            { id: 'FCH7HC', name: 'CAPITALISMO CONTEMPORÂNEO E ECONOMIA POLÍTICA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 70, y: 15.0, type: 'humanities' },
            { id: 'FCH7PA', name: 'PSICOLOGIA DO TRABALHO', dependencies: [], groupId: '[1135]', period: 4, chs: 2, cht: 30, x: 90, y: 15.0, type: 'humanities' },
            { id: 'FCH7PB', name: 'RELAÇÕES INTERPESSOAIS, GRUPO E PODER', dependencies: [], groupId: '[1135]', period: 4, chs: 2, cht: 30, x: 10, y: 25.0, type: 'humanities' },
            { id: 'FCH7SA', name: 'SOCIOLOGIA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 30, y: 25.0, type: 'humanities' },
            { id: 'FCH7SB', name: 'TECNOLOGIA E SOCIEDADE', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 50, y: 25.0, type: 'humanities' },
            { id: 'FCH7SC', name: 'TECNOLOGIA, TRABALHO E SAÚDE', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 70, y: 25.0, type: 'humanities' },
            { id: 'FCH7SD', name: 'SOCIEDADE E POLÍTICA NO BRASIL', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 90, y: 25.0, type: 'humanities' },
            { id: 'FCH7SE', name: 'SOCIEDADE E POLÍTICA NO PARANÁ', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 10, y: 35.0, type: 'humanities' },
            { id: 'FCH7XA', name: 'TECNOLOGIA SOCIAL E ECONOMIA SOLIDÁRIA', dependencies: [], groupId: '[1135]', period: 4, chs: 4, cht: 60, x: 30, y: 35.0, type: 'humanities' },
            { id: 'FCH7XC', name: 'PRESENÇA AFRICANA NO BRASIL', dependencies: [], groupId: '[1135]', period: 4, chs: 2, cht: 30, x: 50, y: 35.0, type: 'humanities' },
            { id: 'FCH7XD', name: 'DIREITOS HUMANOS, SEGURANÇA E DIVERSIDADE', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 70, y: 35.0, type: 'humanities' },
            { id: 'FCH7XE', name: 'POLÍTICAS PÚBLICAS', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 90, y: 35.0, type: 'humanities' },
            { id: 'FCH7XF', name: 'DIMENSÃO AMBIENTAL NA GESTÃO URBANA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 10, y: 45.0, type: 'humanities' },
            { id: 'FCH7XG', name: 'TECNOPOLÍTICAS DA SOCIEDADE CONTEMPORÂNEA', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 30, y: 45.0, type: 'humanities' },
            { id: 'MEC7AV', name: 'Tópicos em Ciências Humanas 1', dependencies: [], groupId: '[1135]', period: 4, chs: 2, cht: 30, x: 50, y: 45.0, type: 'humanities' },
            { id: 'MEC7AX', name: 'Tópicos em Ciências Humanas 2', dependencies: [], groupId: '[1135]', period: 4, chs: 3, cht: 45, x: 70, y: 45.0, type: 'humanities' },
            { id: 'MEC7AZ', name: 'Tópicos em Ciências Humanas 3', dependencies: [], groupId: '[1135]', period: 4, chs: 4, cht: 60, x: 90, y: 45.0, type: 'humanities' },
            // --- Grupo [1222] ---
            { id: 'ARQ7EA', name: 'TOWARDS SUSTAINABILITY', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 10, y: 55.0, type: 'humanities' },
            { id: 'ARQ7EB', name: 'RUMO A SUSTENTABILIDADE', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 30, y: 55.0, type: 'humanities' },
            { id: 'EDU70J', name: 'LIBRAS', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 50, y: 55.0, type: 'humanities' },
            { id: 'EDU7AG', name: 'ESPANHOL PARA ENGENHARIAS 1', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 70, y: 55.0, type: 'humanities' },
            { id: 'EDU7AH', name: 'ESPANHOL PARA ENGENHARIAS 2', dependencies: ["EDU7AG"], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 90, y: 55.0, type: 'humanities' },
            { id: 'EDU7AI', name: 'PRÁTICA DE ESCRITA PARA ENGENHARIAS', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 10, y: 65.0, type: 'humanities' },
            { id: 'ELH01', name: 'FUNDAMENTOS DE PRIMEIROS SOCORROS', dependencies: [], groupId: '[1222]', period: 4, chs: 2, cht: 30, x: 30, y: 65.0, type: 'humanities' },
            { id: 'ELH02', name: 'PRÁTICA DE GRUPO E INTERAÇÕES HUMANAS COM A MÚSICA', dependencies: [], groupId: '[1222]', period: 4, chs: 2, cht: 30, x: 50, y: 65.0, type: 'humanities' },
            { id: 'ELH04', name: 'INOVAÇÃO TECNOLÓGICA E FINANCIAMENTO', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 70, y: 65.0, type: 'humanities' },
            { id: 'ELH05', name: 'NOÇÕES JURÍDICAS PARA EMPREENDEDORES', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 90, y: 65.0, type: 'humanities' },
            { id: 'ELTC1', name: 'METODOLOGIA DA PESQUISA CIENTÍFICA E TECNOLÓGICA', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 10, y: 75.0, type: 'humanities' },
            { id: 'FCH7AA', name: 'DANÇA E TECNOLOGIA', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 30, y: 75.0, type: 'humanities' },
            { id: 'GEE75D', name: 'GESTÃO ESTRATÉGICA', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 50, y: 75.0, type: 'humanities' },
            { id: 'GEE7A1', name: 'FUNDAMENTOS DE ADMINISTRAÇÃO', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 70, y: 75.0, type: 'humanities' },
            { id: 'GEE7AA', name: 'GESTÃO DO CONHECIMENTO', dependencies: [], groupId: '[1222]', period: 4, chs: 2, cht: 30, x: 90, y: 75.0, type: 'humanities' },
            { id: 'GEE7E5', name: 'FUNDAMENTOS DE ENGENHARIA ECONÔMICA E ANÁLISE DE VIABILIDADE', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 10, y: 85.0, type: 'humanities' },
            { id: 'GEE7F1', name: 'FUNDAMENTOS DE FINANÇAS', dependencies: [], equivalents: [{ id: 'GEE7F2', cht: 60 }], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 30, y: 85.0, type: 'humanities' },
            { id: 'GEE7G1', name: 'FUNDAMENTOS DE GESTÃO DE PESSOAS', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 50, y: 85.0, type: 'humanities' },
            { id: 'GEE7G5', name: 'FUNDAMENTOS DE GESTÃO DE PROJETO', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 70, y: 85.0, type: 'humanities' },
            { id: 'GEE7M1', name: 'FUNDAMENTOS DE MARKETING', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 90, y: 85.0, type: 'humanities' },
            { id: 'LEM7SM', name: 'SUSTENTABILIDADE E MEIO AMBIENTE: ESTUDO DE NARRATIVAS AMBIENTAIS', dependencies: [], groupId: '[1222]', period: 4, chs: 2, cht: 30, x: 10, y: 95.0, type: 'humanities' },
            { id: 'MEC7AS', name: 'Tópicos em Humanidades 1', dependencies: [], groupId: '[1222]', period: 4, chs: 2, cht: 30, x: 30, y: 95.0, type: 'humanities' },
            { id: 'MEC7AT', name: 'Tópicos em Humanidades 2', dependencies: [], groupId: '[1222]', period: 4, chs: 3, cht: 45, x: 50, y: 95.0, type: 'humanities' },
            { id: 'MEC7AU', name: 'Tópicos em Humanidades 3', dependencies: [], groupId: '[1222]', period: 4, chs: 4, cht: 60, x: 70, y: 95.0, type: 'humanities' },
            { id: 'QBI7CA', name: 'CIÊNCIAS DO AMBIENTE', dependencies: [], groupId: '[1222]', period: 4, chs: 2, cht: 30, x: 90, y: 95.0, type: 'humanities' },
        ];