const allOptionalNodesData = [
            // --- Trilha [1120] ---
            { id: 'ELE13', name: 'REDES', dependencies: [], equivalents: [{ id: 'ELE21', cht: 45 }], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 10, y: 5.0, type: 'optional' },
            { id: 'ELF74', name: 'SISTEMAS EMBARCADOS', dependencies: ["ELN76B"], equivalents: [{ id: 'CSW41', cht: 60 }, { id: 'ELEW32', cht: 60 }], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 26, y: 5.0, type: 'optional' },
            { id: 'ELF75', name: 'MODELAGEM E SIMULAÇÃO', dependencies: ["ELN77A"], equivalents: [{ id: 'ELT7EF', cht: 60 }], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 42, y: 5.0, type: 'optional' },
            { id: 'ELN7AA', name: 'DESENHO ELETRÔNICO', dependencies: ["ELN72A"], equivalents: [{ id: 'ELB23', cht: 30 }, { id: 'ELEF20', cht: 30 }], groupId: '[1120]', period: 6, chs: 2, cht: 30, x: 58, y: 5.0, type: 'optional' },
            { id: 'ELN7AB', name: 'ENGENHARIA DE SISTEMAS', dependencies: ["ELN74B"], equivalents: [{ id: 'ELEW40', cht: 45 }, { id: 'ELTE1', cht: 45 }], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 74, y: 5.0, type: 'optional' },
            { id: 'ELN7AC', name: 'REDES INDUSTRIAIS', dependencies: ["ELN75B"], equivalents: [{ id: 'ELT85C', cht: 45 }], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 90, y: 5.0, type: 'optional' },
            { id: 'ELN7AD', name: 'SISTEMAS DE SUPERVISÃO', dependencies: ["ELN77B"], equivalents: [{ id: 'ELT77J', cht: 60 }, { id: 'ELT86C', cht: 60 }], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 10, y: 10.1, type: 'optional' },
            { id: 'ELN7AE', name: 'CONTROLE DE PROCESSOS', dependencies: ["ELN77A"], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 26, y: 10.1, type: 'optional' },
            { id: 'ELN7AF', name: 'ELETRÔNICA DE POTÊNCIA B', dependencies: ["ELN77C"], groupId: '[1120]', period: 6, chs: 2, cht: 30, x: 42, y: 10.1, type: 'optional' },
            { id: 'ELN7AG', name: 'Tópicos em Eletrônica', dependencies: [], groupId: '[1120]', period: 6, chs: 2, cht: 30, x: 58, y: 10.1, type: 'optional' },
            { id: 'ELN7AH', name: 'Tópicos em Eletrônica', dependencies: [], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 74, y: 10.1, type: 'optional' },
            { id: 'ELN7AI', name: 'Tópicos em Eletrônica', dependencies: [], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 90, y: 10.1, type: 'optional' },
            { id: 'ELN7AJ', name: 'Tópicos em Eletrônica', dependencies: [], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 10, y: 15.3, type: 'optional' },
            { id: 'ELN7AK', name: 'Eletrônica de Potência', dependencies: ["ELN77C"], groupId: '[1120]', period: 6, chs: 2, cht: 30, x: 26, y: 15.3, type: 'optional' },
            { id: 'ELN7AL', name: 'Internet das Coisas', dependencies: ["ELN75B"], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 42, y: 15.3, type: 'optional' },
            { id: 'ELN7AM', name: 'Desenvolvimento de Projetos Eletrônicos', dependencies: ["ELN72A"], groupId: '[1120]', period: 6, chs: 2, cht: 30, x: 58, y: 15.3, type: 'optional' },
            { id: 'ELN7AN', name: 'Robótica Aplicada', dependencies: ["ELN78A"], equivalents: [{ id: 'ELEW41', cht: 75 }], groupId: '[1120]', period: 6, chs: 5, cht: 75, x: 74, y: 15.3, type: 'optional' },
            { id: 'ELN7AO', name: 'Linux Básico', dependencies: [], equivalents: [{ id: 'ELN8CA', cht: 60 }], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 90, y: 15.3, type: 'optional' },
            { id: 'ELTA2', name: 'BIOENGENHARIA', dependencies: ["ELN76A"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 10, y: 20.4, type: 'optional' },
            { id: 'ELTD1', name: 'INTRODUÇÃO À MODELAGEM E APRENDIZADO', dependencies: ["EST70A"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 26, y: 20.4, type: 'optional' },
            { id: 'ELTD2', name: 'PROCESSAMENTO DE IMAGENS', dependencies: ["Periodo:6"], equivalents: [{ id: 'CSV30', cht: 60 }], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 42, y: 20.4, type: 'optional' },
            { id: 'ELTD4', name: 'RECONHECIMENTO DE PADRÕES E APRENDIZADO DE MÁQUINA', dependencies: ["ELTD1"], groupId: '[1120]', period: 6, chs: 3, cht: 45, x: 58, y: 20.4, type: 'optional' },
            { id: 'ELTD6', name: 'FUNDAMENTOS MATEMÁTICOS PARA SINAIS, IMAGENS E PADRÕES', dependencies: ["EST70A", "MAT7AL"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 74, y: 20.4, type: 'optional' },
            { id: 'ELTD7', name: 'INTRODUÇÃO AO APRENDIZADO DE MÁQUINA', dependencies: ["ELTD6"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 90, y: 20.4, type: 'optional' },
            { id: 'ELTE10', name: 'IDENTIFICAÇÃO DE SISTEMAS', dependencies: ["ELN78A"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 10, y: 25.6, type: 'optional' },
            { id: 'ELTE13', name: 'VEÍCULOS ELÉTRICOS', dependencies: ["ELN77C", "ELN78C"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 26, y: 25.6, type: 'optional' },
            { id: 'ELTE2', name: 'PROGRAMAÇÃO MATEMÁTICA', dependencies: [], equivalents: [{ id: 'CSD41', cht: 45 }], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 42, y: 25.6, type: 'optional' },
            { id: 'ELTE6', name: 'ENERGIA FOTOVOLTAICA', dependencies: [], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 58, y: 25.6, type: 'optional' },
            { id: 'ELTE8', name: 'SISTEMAS NÃO LINEARES', dependencies: ["ELN78A"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 74, y: 25.6, type: 'optional' },
            { id: 'ELTE9', name: 'CONTROLE AUTOMÁTICO', dependencies: ["ELN78A"], groupId: '[1120]', period: 6, chs: 4, cht: 60, x: 90, y: 25.6, type: 'optional' },

            // --- Trilha [1121] ---
            { id: 'MEC78B', name: 'ENGENHARIA ECONÔMICA', dependencies: [], groupId: '[1121]', period: 6, chs: 2, cht: 30, x: 10, y: 34.6, type: 'optional' },
            { id: 'MEC7AA', name: 'PRINCÍPIOS DE MECÂNICA RACIONAL', dependencies: ["MEC74A"], equivalents: [{ id: 'FIS76B', cht: 60 }], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 26, y: 34.6, type: 'optional' },
            { id: 'MEC7AC', name: 'MANUFATURA ADITIVA', dependencies: ["MEC72A"], groupId: '[1121]', period: 6, chs: 3, cht: 45, x: 42, y: 34.6, type: 'optional' },
            { id: 'MEC7AD', name: 'SOLDAGEM', dependencies: ["MEC72B"], equivalents: [{ id: 'MEC75D', cht: 45 }], groupId: '[1121]', period: 6, chs: 3, cht: 45, x: 58, y: 34.6, type: 'optional' },
            { id: 'MEC7AE', name: 'MECANISMOS', dependencies: ["MEC74A"], equivalents: [{ id: 'MEC76F', cht: 60 }], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 74, y: 34.6, type: 'optional' },
            { id: 'MEC7AF', name: 'PROGRAMAÇÃO DE ROBÔS', dependencies: ["ELN77B"], groupId: '[1121]', period: 6, chs: 2, cht: 30, x: 90, y: 34.6, type: 'optional' },
            { id: 'MEC7AG', name: 'CONTROLE ESTATÍSTICO DE PROCESSO', dependencies: ["EST70A"], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 10, y: 39.7, type: 'optional' },
            { id: 'MEC7AH', name: 'SIMULAÇÃO', dependencies: ["MEC76D"], groupId: '[1121]', period: 6, chs: 3, cht: 45, x: 26, y: 39.7, type: 'optional' },
            { id: 'MEC7AI', name: 'TECNOLOGIA ASSISTIVA', dependencies: ["MEC75B"], groupId: '[1121]', period: 6, chs: 3, cht: 45, x: 42, y: 39.7, type: 'optional' },
            { id: 'MEC7AJ', name: 'MANUFATURA AVANÇADA E INDÚSTRIA 4.0', dependencies: ["MEC76D"], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 58, y: 39.7, type: 'optional' },
            { id: 'MEC7AK', name: 'FUNDIÇÃO E CONFORMAÇÃO PLÁSTICA', dependencies: ["MEC72B"], equivalents: [{ id: 'MEC74C', cht: 30 }, { id: 'MEC74D', cht: 30 }], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 74, y: 39.7, type: 'optional' },
            { id: 'MEC7AL', name: 'Tópicos em Mecânica 1', dependencies: [], groupId: '[1121]', period: 6, chs: 2, cht: 30, x: 90, y: 39.7, type: 'optional' },
            { id: 'MEC7AM', name: 'Tópicos em Mecânica 2', dependencies: [], groupId: '[1121]', period: 6, chs: 3, cht: 45, x: 10, y: 44.9, type: 'optional' },
            { id: 'MEC7AN', name: 'Tópicos em Mecânica 3', dependencies: [], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 26, y: 44.9, type: 'optional' },
            { id: 'MEC7AO', name: 'Tópicos em Mecânica 4', dependencies: [], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 42, y: 44.9, type: 'optional' },
            { id: 'MEC7AP', name: 'Programação de Robôs', dependencies: ["ELN77B"], groupId: '[1121]', period: 6, chs: 2, cht: 30, x: 58, y: 44.9, type: 'optional' },
            { id: 'MEC7AQ', name: 'Manufatura Avançada e Indústria 4.0', dependencies: ["MEC76D"], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 74, y: 44.9, type: 'optional' },
            { id: 'MEC7AR', name: 'Simulação', dependencies: ["MEC76D"], groupId: '[1121]', period: 6, chs: 3, cht: 45, x: 90, y: 44.9, type: 'optional' },
            { id: 'MEC7CO', name: 'PRODUÇÃO ENXUTA', dependencies: ["MEC76D"], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 10, y: 50.0, type: 'optional' },
            { id: 'MEC7EE', name: 'GESTÃO DE CARREIRA', dependencies: [], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 26, y: 50.0, type: 'optional' },
            { id: 'MEC7GF', name: 'SIMULAÇÃO DE PROJETOS MECÂNICOS', dependencies: ["MEC76A"], groupId: '[1121]', period: 6, chs: 4, cht: 60, x: 42, y: 50.0, type: 'optional' },

            // --- Trilha [1224] ---
            { id: 'ARQ7DH', name: 'DESIGN THINKING PARA INOVAÇÃO', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 10, y: 59.0, type: 'optional' },
            { id: 'ARQ7EC', name: 'PRÁTICAS DE EXTENSÃO UNIVERSITÁRIA', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 26, y: 59.0, type: 'optional' },
            { id: 'CAART01', name: 'TÓPICOS EM MÚSICA E TECNOLOGIA: HISTÓRIA DO JAZZ', dependencies: [], groupId: '[1224]', period: 2, chs: 2, cht: 30, x: 42, y: 59.0, type: 'optional' },
            { id: 'CAART02', name: 'PRÁTICA MUSICAL E INTERAÇÕES HUMANAS: APRENDIZADO COLETIVO DE VIOLINO, VIOLA ERUDITA, VIOLONCELO E CONTRABAIXO ACÚSTICO 1', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 58, y: 59.0, type: 'optional' },
            { id: 'CAART03', name: 'PRÁTICA MUSICAL E INTERAÇÕES HUMANAS: APRENDIZADO COLETIVO DE VIOLINO, VIOLA ERUDITA, VIOLONCELO E CONTRABAIXO ACÚSTICO 2', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 74, y: 59.0, type: 'optional' },
            { id: 'CAART04', name: 'PRÁTICA ARTÍSTICA MUSICAL: GRUPOS INSTRUMENTAIS 1', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 90, y: 59.0, type: 'optional' },
            { id: 'CAART05', name: 'PRÁTICA ARTÍSTICA MUSIAL: GRUPOS INSTRUMENTAIS 2', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 10, y: 64.1, type: 'optional' },
            { id: 'CAART06', name: 'PRÁTICA ARTÍSTICA MUSICAL: GRUPOS INSTRUMENTAIS 3', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 26, y: 64.1, type: 'optional' },
            { id: 'CAART07', name: 'PRÁTICA ARTÍSTICA MUSICAL: GRUPOS INSTRUMENTAIS 4', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 42, y: 64.1, type: 'optional' },
            { id: 'CAART08', name: 'INTRODUÇÃO NA PRÁTICA DE CANTO, TEORIA E SOLFEJO MUSICAL 1', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 58, y: 64.1, type: 'optional' },
            { id: 'CAART09', name: 'INTROCUÇÃO NA PRÁTICA DE CANTO, TEORIA E SOLFEJO MUSICAL 2', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 74, y: 64.1, type: 'optional' },
            { id: 'CAART10', name: 'PRÁTICAS DE VIOLÃO POPULAR E MPB 1', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 90, y: 64.1, type: 'optional' },
            { id: 'CAART11', name: 'PRÁTICA DE VIOLÃO POPULAR E MPB 2', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 10, y: 69.3, type: 'optional' },
            { id: 'CAART12', name: 'CANTO CORAL 1', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 26, y: 69.3, type: 'optional' },
            { id: 'CAART13', name: 'CANTO CORAL 2', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 42, y: 69.3, type: 'optional' },
            { id: 'CAART14', name: 'CANTO CORAL 3', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 58, y: 69.3, type: 'optional' },
            { id: 'CAART15', name: 'CANTO CORAL 4', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 74, y: 69.3, type: 'optional' },
            { id: 'CAART16', name: 'TÉCNICA VOCAL E AFINAÇÃO', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 90, y: 69.3, type: 'optional' },
            { id: 'CAART17', name: 'CANTO, FONÉTICA E FONOLOGIA', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 10, y: 74.4, type: 'optional' },
            { id: 'CAART21', name: 'TÓPICOS EM PENSAMENTO COMPUTACIONAL E MÚSICA', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 26, y: 74.4, type: 'optional' },
            { id: 'CAART22', name: 'COMPUTAÇÃO MUSICAL', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 42, y: 74.4, type: 'optional' },
            { id: 'CAART23', name: 'CRIATIVIDADE E PROCESSOS CRIATIVOS', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 58, y: 74.4, type: 'optional' },
            { id: 'CAART24', name: 'TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO NA EDUCAÇÃO', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 74, y: 74.4, type: 'optional' },
            { id: 'CAART25', name: 'PROJETOS STEAM (SCIENCE, TECHNOLOGY, ENGINEERING, ARTS, MATHEMATICS)', dependencies: [], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 90, y: 74.4, type: 'optional' },
            { id: 'DIN7HU', name: 'PROJETOS PARA PESSOAS: LABORATÓRIO DE DESIGN E INOVAÇÃO SOCIAL', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 10, y: 79.6, type: 'optional' },
            { id: 'ELN7AP', name: 'Práticas de Desenvolvimento para Linux Avançado', dependencies: ["ELN7AO"], equivalents: [{ id: 'ELN8CC', cht: 90 }], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 26, y: 79.6, type: 'optional' },
            { id: 'ELN7AQ', name: 'Segurança da Informação na Prática', dependencies: [], equivalents: [{ id: 'ELN8DH', cht: 120 }], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 42, y: 79.6, type: 'optional' },
            { id: 'ELN7AR', name: 'Gestão de Produtos Digitais', dependencies: [], equivalents: [{ id: 'ELN8EB', cht: 90 }], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 58, y: 79.6, type: 'optional' },
            { id: 'ELN7AS', name: 'Cabeamento Estruturado na Prática', dependencies: ["ELE13"], equivalents: [{ id: 'ELN8DG', cht: 105 }], groupId: '[1224]', period: 2, chs: 7, cht: 105, x: 74, y: 79.6, type: 'optional' },
            { id: 'ELN8BD', name: 'ENGENHARIA DE PROMPT', dependencies: ["ELN74B"], groupId: '[1224]', period: 2, chs: 5, cht: 75, x: 90, y: 79.6, type: 'optional' },
            { id: 'ELN8CD', name: 'DESENVOLVIMENTO PARA SISTEMAS GNU/ LINUX', dependencies: ["ELN7AO"], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 10, y: 84.7, type: 'optional' },
            { id: 'ELN8DI', name: 'TECHNOLOGICAL CRAFTSMANSHIP WORKS', dependencies: ["Periodo:4"], groupId: '[1224]', period: 2, chs: 7, cht: 105, x: 26, y: 84.7, type: 'optional' },
            { id: 'ELN8DJ', name: 'VISÃO PRÁTICA DA GESTÃO DA SEGURANÇA DA INFORMAÇÃO E SUAS APLICAÇÕES', dependencies: ["ELE13"], groupId: '[1224]', period: 2, chs: 8, cht: 120, x: 42, y: 84.7, type: 'optional' },
            { id: 'ELN8DK', name: 'ESTUDOS DE CASOS E PROJETOS DE CABEAMENTO ESTRUTURADO', dependencies: ["ELE13"], groupId: '[1224]', period: 2, chs: 7, cht: 105, x: 58, y: 84.7, type: 'optional' },
            { id: 'ELN8EC', name: 'INTRODUÇÃO À SUSTENTABILIDADE AMBIENTAL', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 74, y: 84.7, type: 'optional' },
            { id: 'FCH7AB', name: 'QUESTÕES CONTEMPORÂNEAS DO CORPO', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 90, y: 84.7, type: 'optional' },
            { id: 'FCH7PC', name: 'PLANEJAMENTO DE CARREIRA', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 10, y: 89.9, type: 'optional' },
            { id: 'FCH7SF', name: 'POLÍTICA, INSTITUIÇÕES E CIDADANIA NO PARANÁ', dependencies: [], groupId: '[1224]', period: 2, chs: 4, cht: 60, x: 26, y: 89.9, type: 'optional' },
            { id: 'FCH7XB', name: 'PRESENÇA AFRICANA NO BRASIL: TECNOLOGIA, TRABALHO E CULTURA', dependencies: [], groupId: '[1224]', period: 2, chs: 3, cht: 45, x: 42, y: 89.9, type: 'optional' },
            { id: 'GEE72H', name: 'A PRÁTICA DA EXTENSÃO UNIVERSITÁRIA', dependencies: [], groupId: '[1224]', period: 2, chs: 2, cht: 30, x: 58, y: 89.9, type: 'optional' },
            { id: 'GEE73C', name: 'MATEMÁTICA FINANCEIRA', dependencies: [], groupId: '[1224]', period: 2, chs: 3, cht: 45, x: 74, y: 89.9, type: 'optional' },
            { id: 'GEE76A', name: 'ELABORAÇÃO E GESTÃO DE PROJETOS', dependencies: [], groupId: '[1224]', period: 2, chs: 3, cht: 45, x: 90, y: 89.9, type: 'optional' },
            { id: 'LICOM7AA', name: 'UNICAÇÃO E EDUCAÇÃO', dependencies: [], groupId: '[1224]', period: 2, chs: 6, cht: 90, x: 10, y: 95.0, type: 'optional' },
            { id: 'LICOM7AB', name: 'UNICAÇÃO, SOCIEDADE E EVENTOS SMART CHALLENGES SMART PROJECTS', dependencies: [], groupId: '[1224]', period: 2, chs: 7, cht: 105, x: 26, y: 95.0, type: 'optional' },

        ];